backend/call/urls.py
from django.urls import include, path

from backend.call import views as v

app_name = 'call'

call_patterns = [
    path('', v.CallListView.as_view(), name='call_list'),
    path('<int:pk>/', v.CallDetailView.as_view(), name='call_detail'),
    path('create/', v.CallCreateView.as_view(), name='call_create'),
    path('<int:pk>/update/', v.CallUpdateView.as_view(), name='call_update'),
    path('<int:pk>/delete/', v.CallDeleteView.as_view(), name='call_delete'),
    path('management/', v.call_management, name='call_management'),
]

category_patterns = [
    path('', v.CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/', v.CategoryDetailView.as_view(), name='category_detail'),
    path('create/', v.CategoryCreateView.as_view(), name='category_create'),
    path('<int:pk>/update/', v.CategoryUpdateView.as_view(), name='category_update'),  # noqa E501
    path('<int:pk>/delete/', v.CategoryDeleteView.as_view(), name='category_delete'),  # noqa E501
]

subcategory_patterns = [
    path('', v.SubcategoryListView.as_view(), name='subcategory_list'),
    path('<int:pk>/', v.SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('create/', v.SubcategoryCreateView.as_view(), name='subcategory_create'),
    path('<int:pk>/update/', v.SubcategoryUpdateView.as_view(), name='subcategory_update'),  # noqa E501
    path('<int:pk>/delete/', v.SubcategoryDeleteView.as_view(), name='subcategory_delete'),  # noqa E501
    path('choices/ajax/', v.subcategory_choices_ajax, name='subcategory_choices_ajax'),  # noqa E501
]


urlpatterns = [
    path('call/', include(call_patterns)),
    path('category/', include(category_patterns)),
    path('subcategory/', include(subcategory_patterns)),
]

backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .api import api

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('accounts/', include('backend.accounts.urls')),  # sem namespace
    path('call/', include('backend.call.urls', namespace='call')),
    path('admin/', admin.site.urls),
    path('api/v1/', api.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

backend/core/models.py
from django.db import models

from backend.accounts.models import User


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class CreatedBy(models.Model):
    created_by = models.ForeignKey(
        User,
        verbose_name='criado por',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True

backend/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from backend.call.constants import CONCLUDED, IN_PROGRESS, OPEN
from backend.call.models import Call
from backend.utils.utils import has_group


@login_required
def index(request):
    template_name = 'index.html'

    queryset = Call.objects.all()

    if has_group(request.user, 'Padrão'):
        queryset = queryset.filter(user=request.user)

    open_status = queryset.filter(status=OPEN).count()
    in_progress_status = queryset.filter(status=IN_PROGRESS).count()
    concluded_status = queryset.filter(status=CONCLUDED).count()

    context = {
        'open_status': open_status,
        'in_progress_status': in_progress_status,
        'concluded_status': concluded_status,
    }
    return render(request, template_name, context)

backend/core/templates/includes/asidebar.html
{% load static %}
<aside class="aside-menu">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">
        <i class="icon-list"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#messages" role="tab">
        <i class="icon-speech"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#settings" role="tab">
        <i class="icon-settings"></i>
      </a>
    </li>
  </ul>
  <!-- Tab panes-->
  <div class="tab-content">
    <div class="tab-pane active" id="timeline" role="tabpanel">
      <div class="list-group list-group-accent">
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Today</div>
        <div class="list-group-item list-group-item-accent-warning list-group-item-divider">
          <div class="avatar float-right">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
          </div>
          <div>Meeting with
            <strong>Lucas</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
            <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-info">
          <div class="avatar float-right">
            <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="avatar">
          </div>
          <div>Skype with
            <strong>Megan</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  4 - 5pm</small>
          <small class="text-muted">
            <i class="icon-social-skype"></i>  On-line</small>
        </div>
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Tomorrow</div>
        <div class="list-group-item list-group-item-accent-danger list-group-item-divider">
          <div>New UI Project -
            <strong>deadline</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  10 - 11pm</small>
          <small class="text-muted">
            <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/2.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/3.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="avatar">
            </div>
          </div>
        </div>
        <div class="list-group-item list-group-item-accent-success list-group-item-divider">
          <div>
            <strong>#10 Startups.Garden</strong> Meetup</div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
            <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-primary list-group-item-divider">
          <div>
            <strong>Team meeting</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  4 - 6pm</small>
          <small class="text-muted">
            <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/2.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/3.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/8.jpg' %}" alt="avatar">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane p-3" id="messages" role="tabpanel">
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="avatar">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
    </div>
    <div class="tab-pane p-3" id="settings" role="tabpanel">
      <h6>Settings</h6>
      <div class="aside-options">
        <div class="clearfix mt-4">
          <small>
            <b>Option 1</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 2</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 3</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 4</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <hr>
      <h6>System Utilization</h6>
      <div class="text-uppercase mb-1 mt-4">
        <small>
          <b>CPU Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">348 Processes. 1/4 Cores.</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>Memory Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">11444GB/16384MB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>SSD 1 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">243GB/256GB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>SSD 2 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-success" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">25GB/256GB</small>
    </div>
  </div>
</aside>

backend/core/templates/includes/footer.html
<footer class="app-footer">
  <div>
    <a href=".">TCM-RJ</a>
    <span>&copy; 2021</span>
  </div>
  <div class="ml-auto">
    <span>Powered by</span>
    <a href="https://github.com/rg3915/tcmrj-challenge">rg3915</a>
  </div>
</footer>

backend/core/templates/includes/modal.html
<div class="modal fade" id="mymodal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          <label for="firstname">Name</label>
          <input id="firstname" name="firstname" class="form-control" type="text" placeholder="Name" />
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/core/templates/includes/navbar.html
{% load static %}
{% load usergroup_tags %}

<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'core:index' %}">
    <img class="navbar-brand-full" src="{% static 'img/brand/logo.svg' %}" width="89" height="25" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="{% static 'img/brand/sygnet.svg' %}" width="30" height="30" alt="CoreUI Logo">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav d-md-down-none">
    {% if request.user|name_group == 'Padrão' %}
      <li class="nav-item px-3">
        <a class="btn btn-primary" href="{% url 'call:call_create' %}">
          Abertura de Chamado
        </a>
      </li>
    {% endif %}
    <li class="nav-item px-3">
      <a class="nav-link" href="{% url 'call:call_list' %}">
        <i class="icon-bubbles"></i>
        Chamados
      </a>
    </li>
    {% if request.user|name_group == 'Gestor' %}
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'call:call_management' %}">
          <i class="icon-wrench"></i>
          Gerenciamento de Abertura de Chamados
        </a>
      </li>
    {% endif %}
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <!-- <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
        <span class="badge badge-pill badge-danger">5</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 notifications</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="icon-user-follow text-success"></i> New user registered</a>
        <a class="dropdown-item" href="#">
          <i class="icon-user-unfollow text-danger"></i> User deleted</a>
        <a class="dropdown-item" href="#">
          <i class="icon-chart text-info"></i> Sales report is ready</a>
        <a class="dropdown-item" href="#">
          <i class="icon-basket-loaded text-primary"></i> New client</a>
        <a class="dropdown-item" href="#">
          <i class="icon-speedometer text-warning"></i> Server overloaded</a>
        <div class="dropdown-header text-center">
          <strong>Server</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>CPU Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">348 Processes. 1/4 Cores.</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>Memory Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">11444GB/16384MB</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>SSD 1 Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">243GB/256GB</small>
        </a>
      </div>
    </li> -->
    <!-- <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-list"></i>
        <span class="badge badge-pill badge-warning">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 pending tasks</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Upgrade NPM &amp; Bower
            <span class="float-right">
              <strong>0%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">ReactJS Version
            <span class="float-right">
              <strong>25%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">VueJS Version
            <span class="float-right">
              <strong>50%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Add new layouts
            <span class="float-right">
              <strong>75%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Angular 2 Cli Version
            <span class="float-right">
              <strong>100%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all tasks</strong>
        </a>
      </div>
    </li> -->
    <!-- <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-envelope-letter"></i>
        <span class="badge badge-pill badge-info">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 4 messages</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-success"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">Just now</small>
            </div>
            <div class="text-truncate font-weight-bold">
              <span class="fa fa-exclamation text-danger"></span> Important message</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-warning"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">5 minutes ago</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-danger"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">1:52 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-info"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">4:03 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all messages</strong>
        </a>
      </div>
    </li> -->
    <li class="nav-item dropdown d-md-down-none">
      {{ request.user.get_full_name }} - {{ request.user|name_group }}
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" href="{% url 'logout' %}">
        <i class="icon-logout"></i>
      </a>
    </li>
  </ul>
  <!-- <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
    <span class="navbar-toggler-icon"></span>
  </button> -->
</header>

backend/core/templates/includes/sidebar.html
{% load usergroup_tags %}

<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:index' %}">
          <i class="nav-icon icon-speedometer"></i> Dashboard
          <!-- <span class="badge badge-primary">NEW</span> -->
        </a>
      </li>
      <li class="nav-title">Chamados</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'call:call_list' %}">
          <i class="nav-icon icon-bubbles"></i> Chamados</a>
      </li>
      {% if request.user|name_group == 'Gestor' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'call:category_list' %}">
            <i class="nav-icon icon-organization"></i> Categorias</a>
        </li>
      {% endif %}
      {% if request.user|name_group == 'Gestor' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'call:subcategory_list' %}">
            <i class="nav-icon icon-tag"></i> Subcategorias</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>