backend/call/urls.py
from django.urls import include, path

from backend.call import views as v

app_name = 'call'

call_patterns = [
    path('', v.CallListView.as_view(), name='call_list'),
    path('<int:pk>/', v.CallDetailView.as_view(), name='call_detail'),
    path('create/', v.CallCreateView.as_view(), name='call_create'),
    path('<int:pk>/update/', v.CallUpdateView.as_view(), name='call_update'),
    path('<int:pk>/delete/', v.CallDeleteView.as_view(), name='call_delete'),
    path('management/', v.call_management, name='call_management'),
]

category_patterns = [
    path('', v.CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/', v.CategoryDetailView.as_view(), name='category_detail'),
    path('create/', v.CategoryCreateView.as_view(), name='category_create'),
    path('<int:pk>/update/', v.CategoryUpdateView.as_view(), name='category_update'),  # noqa E501
    path('<int:pk>/delete/', v.CategoryDeleteView.as_view(), name='category_delete'),  # noqa E501
]

subcategory_patterns = [
    path('', v.SubcategoryListView.as_view(), name='subcategory_list'),
    path('<int:pk>/', v.SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('create/', v.SubcategoryCreateView.as_view(), name='subcategory_create'),
    path('<int:pk>/update/', v.SubcategoryUpdateView.as_view(), name='subcategory_update'),  # noqa E501
    path('<int:pk>/delete/', v.SubcategoryDeleteView.as_view(), name='subcategory_delete'),  # noqa E501
    path('choices/ajax/', v.subcategory_choices_ajax, name='subcategory_choices_ajax'),  # noqa E501
]


urlpatterns = [
    path('call/', include(call_patterns)),
    path('category/', include(category_patterns)),
    path('subcategory/', include(subcategory_patterns)),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .api import api

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('accounts/', include('backend.accounts.urls')),  # sem namespace
    path('call/', include('backend.call.urls', namespace='call')),
    path('admin/', admin.site.urls),
    path('api/v1/', api.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

backend/call/models.py
from auditlog.registry import auditlog
from django.db import models
from django.urls import reverse_lazy

from backend.accounts.models import User
from backend.core.models import CreatedBy, TimeStampedModel

from .constants import STATUS


class Category(TimeStampedModel):
    title = models.CharField('título', max_length=100, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('call:category_detail', kwargs={'pk': self.pk})

    @property
    def get_list_url(self):
        return reverse_lazy('call:category_list')

    @property
    def get_update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:category_update', kwargs=kw)
        return None

    @property
    def get_delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:category_delete', kwargs=kw)
        return None

    def get_verbose_name(self):
        return self._meta.verbose_name.title()

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural.title()


class Subcategory(TimeStampedModel):
    title = models.CharField('título', max_length=100, unique=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='categoria',
        related_name='subcategories',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'subcategoria'
        verbose_name_plural = 'subcategorias'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('call:subcategory_detail', kwargs={'pk': self.pk})

    @property
    def get_list_url(self):
        return reverse_lazy('call:subcategory_list')

    @property
    def get_update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:subcategory_update', kwargs=kw)
        return None

    @property
    def get_delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:subcategory_delete', kwargs=kw)
        return None

    def get_verbose_name(self):
        return self._meta.verbose_name.title()

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural.title()


class Call(CreatedBy, TimeStampedModel):
    title = models.CharField('título', max_length=100)
    description = models.TextField('descrição')
    status = models.CharField('status', max_length=1, choices=STATUS, default='a')  # noqa E501
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name='atendente',
        related_name='call_users',
        null=True,
        blank=True
    )
    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.SET_NULL,
        verbose_name='subcategoria',
        related_name='subcategories',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'chamado'
        verbose_name_plural = 'chamados'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('call:call_detail', kwargs={'pk': self.pk})

    @property
    def get_list_url(self):
        return reverse_lazy('call:call_list')

    @property
    def get_update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:call_update', kwargs=kw)
        return None

    @property
    def get_delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('call:call_delete', kwargs=kw)
        return None

    def get_verbose_name(self):
        return self._meta.verbose_name.title()

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural.title()


auditlog.register(Call)

backend/core/models.py
from django.db import models

from backend.accounts.models import User


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class CreatedBy(models.Model):
    created_by = models.ForeignKey(
        User,
        verbose_name='criado por',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True

backend/call/forms.py
# from backend.accounts.models import User
from django import forms

from backend.utils.utils import has_group

from .models import Call, Category, Subcategory


class CallForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        label='Categoria',
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Call
        fields = (
            'title',
            'description',
            'status',
            'created_by',
            'user',
            'category',
            'subcategory',
        )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        if has_group(self.request.user, 'Padrão'):
            self.fields['user'].widget = forms.HiddenInput()
            self.fields['created_by'].widget = forms.HiddenInput()
            self.fields['status'].widget.attrs['hidden'] = True

        if has_group(self.request.user, 'Suporte'):
            for field_name, field in self.fields.items():
                if field_name in ('title', 'description'):
                    field.widget.attrs['readonly'] = True

                if field_name in ('status', 'category', 'subcategory', 'created_by'):
                    field.widget.attrs['hidden'] = True

        if has_group(self.request.user, 'Gestor'):
            self.fields['created_by'].widget.attrs['hidden'] = True

    def clean(self):
        self.cleaned_data = super().clean()

        if not self.cleaned_data.get('created_by'):
            self.cleaned_data['created_by'] = self.request.user

        return self.cleaned_data


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class SubcategoryForm(forms.ModelForm):

    class Meta:
        model = Subcategory
        fields = '__all__'

backend/call/views.py
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from backend.core.mixins import ObjectModel, TotalItems

from .forms import CallForm, CategoryForm, SubcategoryForm
from .mixins import FormKwargsMixin, SearchCallMixin
from .models import Call, Category, Subcategory


class CallListView(LRM, TotalItems, SearchCallMixin, ListView):
    model = Call
    paginate_by = 20


class CallDetailView(LRM, DetailView):
    model = Call


class CallCreateView(LRM, ObjectModel, FormKwargsMixin, CreateView):
    model = Call
    form_class = CallForm


class CallUpdateView(LRM, FormKwargsMixin, UpdateView):
    model = Call
    form_class = CallForm


class CallDeleteView(LRM, DeleteView):
    model = Call
    success_url = reverse_lazy('call:call_list')


class CategoryListView(LRM, TotalItems, SearchCallMixin, ListView):
    model = Category
    paginate_by = 20


class CategoryDetailView(LRM, DetailView):
    model = Category


class CategoryCreateView(LRM, ObjectModel, CreateView):
    model = Category
    form_class = CategoryForm


class CategoryUpdateView(LRM, UpdateView):
    model = Category
    form_class = CategoryForm


class CategoryDeleteView(LRM, DeleteView):
    model = Category
    success_url = reverse_lazy('call:category_list')


class SubcategoryListView(LRM, TotalItems, SearchCallMixin, ListView):
    model = Subcategory
    paginate_by = 20


class SubcategoryDetailView(LRM, DetailView):
    model = Subcategory


class SubcategoryCreateView(LRM, ObjectModel, CreateView):
    model = Subcategory
    form_class = SubcategoryForm


class SubcategoryUpdateView(LRM, UpdateView):
    model = Subcategory
    form_class = SubcategoryForm


class SubcategoryDeleteView(LRM, DeleteView):
    model = Subcategory
    success_url = reverse_lazy('call:subcategory_list')


def call_management(request):
    template_name = 'call/management.html'
    return render(request, template_name)


def subcategory_choices_ajax(request):
    template_name = 'call/includes/subcategory_choices.html'
    category_id = request.GET.get('category_id')
    object_list = Subcategory.objects.all()

    if category_id:
        object_list = object_list.filter(category=category_id)

    context = {'object_list': object_list}
    return render(request, template_name, context)

backend/call/templates/call/call_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'call:call_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

backend/call/templates/call/call_detail.html
{% extends "base.html" %}
{% load static %}
{% load usergroup_tags %}

{% block breadcrumb %}
  {% include "breadcrumb/_include_breadcrumb_base_detail.html" %}
{% endblock breadcrumb %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        {{ object.title }}
        <!-- <div class="btn-group float-right">
          <button class="btn btn-setting dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="icon-settings"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div> -->
        {% if request.user|name_group != 'Padrão' %}
          <span class="pull-right btn btn-sm btn-primary mr-2">
            <a href="{{ object.get_update_url }}" class="text-white">
              <i class="fa fa-edit"></i> Editar
            </a>
          </span>
        {% endif %}
      </div>
      <div class="card-body">
        <div class="row">
          <!-- <div class="col-6">
            <img src="https://randomuser.me/api/portraits/lego/5.jpg" width="200px">
          </div> -->
          <div class="col-12">
            <!-- <h4>John Joe</h4> -->
            <h4><small><span class="text-muted">Status</span></small>
              {% if object.status == 'a' %}
                <span class="float-right">
                  <span class="badge badge-success">{{ object.get_status_display }}</span>
                </span>
              {% elif object.status == 'b' %}
                <span class="float-right">
                  <span class="badge badge-warning">{{ object.get_status_display }}</span>
                </span>
              {% else %}
                <span class="float-right">
                  <span class="badge badge-secondary">{{ object.get_status_display }}</span>
                </span>
              {% endif %}
            </h4>
            <hr>
            <h4><small><span class="text-muted">Data</span></small>
              <span class="float-right">{{ object.created|date:"d/m/Y" }}</span>
            </h4>
            <hr>
            <h4><small><span class="text-muted">Descrição</span></small> <br>
              <span class="float-right">{{ object.description }}</span>
            </h4>
            <hr>
            <h4><small><span class="text-muted">Categoria</span></small>
              <span class="float-right">{{ object.subcategory.category }}</span>
            </h4>
            <hr>
            <h4><small><span class="text-muted">Subcategoria</span></small>
              <span class="float-right">{{ object.subcategory }}</span>
            </h4>
            <hr>
            <h4><small><span class="text-muted">Atendente</span></small>
              <span class="float-right">{{ object.user.get_full_name }}</span>
            </h4>
            <hr>
            <h4><small><span class="text-muted">Criado por</span></small>
              <span class="float-right">{{ object.created_by.get_full_name }}</span>
            </h4>
          </div>
        </div>
      </div>
      <!-- <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4>Title</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Title</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
            <li class="list-group-item no-border"><span class="text-muted">Label:</span> Lorem ipsum</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Observation</h4>
          <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, ex, corrupti! Assumenda, distinctio quasi magnam delectus qui et illum reiciendis ea consequuntur mollitia? Mollitia in enim labore consectetur nostrum corrupti.</p>
        </li>
      </ul> -->
    </div>
  </div>
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Contacts
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item no-border">
            <span class="badge badge-warning">type</span> 11 98765-4321
            <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
              <i class="fa fa-edit" style="margin-left: 10px;"></i>
            </span>
          </li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="text-muted">Label:</span> <span class="lead">text</span>
                <span class="span-is-link float-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div>
        -- card-body --
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="lead">Name</span>
                <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span> text</li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span> text</li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span> text</li>
              <li class="list-group-item no-border li-line pl-0 pr-0"><span class="text-muted">Label:</span>
                <span class="badge badge-success">Yes</span>
              </li>
              <li class="list-group-item li-line pl-0 pr-0">
                <span class="text-muted">Observation:</span>
                <p class="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda tenetur alias cupiditate dicta blanditiis facilis rerum animi at unde, fugit. Aliquid quos, id illo autem praesentium. Amet reprehenderit rerum, veritatis.</p>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <!-- <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal">
          <i class="fa fa-plus"></i> Add
        </span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-12">
            <table class="table table-responsive-sm table-hover table-striped">
              <thead>
                <tr>
                  <th>Username</th>
                  <th>Date registered</th>
                  <th>Role</th>
                  <th class="text-center">Status</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    Chetan Mohamed
                  </td>
                  <td>2020/01/01</td>
                  <td>Member</td>
                  <td class="text-center">
                    <span class="badge badge-success">Active</span>
                  </td>
                  <td class="text-center">
                    <a href="">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    Derick Maximinus
                  </td>
                  <td>2020/02/01</td>
                  <td>Staff</td>
                  <td class="text-center">
                    <span class="badge badge-danger">Banned</span>
                  </td>
                  <td class="text-center">
                    <a href="">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    Estavan Lykos
                  </td>
                  <td>2020/02/01</td>
                  <td>Admin</td>
                  <td class="text-center">
                    <span class="badge badge-secondary">Inactive</span>
                  </td>
                  <td class="text-center">
                    <a href="">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    Friderik Dávid
                  </td>
                  <td>2020/03/01</td>
                  <td>Member</td>
                  <td class="text-center">
                    <span class="badge badge-warning">Pending</span>
                  </td>
                  <td class="text-center">
                    <a href="">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    Samppa Nori
                  </td>
                  <td>2020/01/21</td>
                  <td>Staff</td>
                  <td class="text-center">
                    <span class="badge badge-success">Active</span>
                  </td>
                  <td class="text-center">
                    <a href="">
                      <i class="fa fa-edit"></i>
                    </a>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div> -->
</div>
<!-- Modal -->
{% include "includes/modal.html" %}
{% endblock content %}

backend/call/templates/call/call_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block breadcrumb %}
  {% if object.pk %}
    {% include "breadcrumb/_include_breadcrumb_base_edit.html" %}
  {% else %}
    {% include "breadcrumb/_include_breadcrumb_base_add.html" %}
  {% endif %}
{% endblock breadcrumb %}

{% block content %}
<div class="col-lg-12">
  <div class="card">
    <div class="card-header">
      <strong>{% if object.pk %}
        Editar: {{ object }}
      {% else %}
        Adicionar: {{ object.get_verbose_name }}</strong>
      {% endif %}
      <!-- <small>Form</small> -->
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
          <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
            <span class="required">{{ field.label }}</span>
            {% else %}
            {{ field.label }}
            {% endif %}
          </label>
          {% render_field field class="form-control" %}
          {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="float-right">
          <button class="btn btn-primary" type="submit">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function() {
      $('.use-select2').select2();

      if ($('#id_status').is(":hidden")) {
        $("label[for='id_status']").css("display", "none")
      }

      if ($('#id_category').is(":hidden")) {
        $("label[for='id_category']").css("display", "none")
      }

      if ($('#id_subcategory').is(":hidden")) {
        $("label[for='id_subcategory']").css("display", "none")
      }

      if ($('#id_created_by').is(":hidden")) {
        $("label[for='id_created_by']").css("display", "none")
      }
    });

    $('#id_category').on('change', function() {
      let url = '/call/subcategory/choices/ajax/?category_id=' +  this.value
      $.ajax({
        url: url,
        type: 'GET',
        success: function(response) {
          $('#id_subcategory').html(response);
        },
        error: function(xhr) {
          // body... xhr.statusText + xhr.responseText
        },
        complete: function() {
          // body...
        }
      })
    });
  </script>
{% endblock js %}

backend/call/templates/call/call_list.html
{% extends "base.html" %}
{% load static %}
{% load usergroup_tags %}

{% block breadcrumb %}
  {% include "breadcrumb/_include_breadcrumb_base.html" %}
{% endblock breadcrumb %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Lista de Chamados
        <span class="float-right">{{ object_list.count }} de {{ page_obj.paginator.count }} resultados ({{ total_items }} total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          {% if request.user|name_group == 'Padrão' %}
            <div class="col-md-auto">
              <a class="btn btn-primary" href="{% url 'call:call_create' %}">
                <i class="fa fa-plus"></i>
                Adicionar
              </a>
            </div>
          {% endif %}
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Buscar..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
              <div class="float-right p-2">
                <a href="?status=a">
                  <span class="badge badge-success">Aberto</span>
                </a>
                <a href="?status=b">
                  <span class="badge badge-warning">Em andamento</span>
                </a>
                <a href="?status=c">
                  <span class="badge badge-secondary">Concluído</span>
                </a>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>Data</th>
              <th>Título</th>
              <th>Descrição</th>
              <th>Atendente</th>
              <th>Criado por</th>
              <th class="text-center">Status</th>
              <th>Categoria</th>
              <th>Subcategoria</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td>{{ object.pk }}</td>
                <td>{{ object.created|date:"d/m/Y" }}</td>
                <td>
                  <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                </td>
                <td>{{ object.description }}</td>
                <td>{{ object.user.get_full_name }}</td>
                <td>{{ object.created_by.get_full_name }}</td>
                <td class="text-center">
                  {% if object.status == 'a' %}
                    <span class="badge badge-success">{{ object.get_status_display }}</span>
                  {% elif object.status == 'b' %}
                    <span class="badge badge-warning">{{ object.get_status_display }}</span>
                  {% else %}
                    <span class="badge badge-secondary">{{ object.get_status_display }}</span>
                  {% endif %}
                </td>
                <td>
                  {{ object.subcategory.category }}
                </td>
                <td>
                  {{ object.subcategory }}
                </td>
                <!-- <td class="text-center">
                  <span class="badge badge-success">Active</span>
                </td> -->
                <td class="text-center">
                  {% if request.user|name_group != 'Padrão' %}
                    <a href="{{ object.get_update_url }}">
                      <i class="fa fa-edit"></i>
                    </a>
                  {% endif %}
                  {% if request.user|name_group == 'Gestor' %}
                    <a href="{{ object.get_delete_url }}">
                      <i class="fa fa-close no" style="padding-left:5px"></i>
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

backend/call/templates/call/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'call:category_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

backend/call/templates/call/subcategory_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'call:subcategory_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}